kind: Service
apiVersion: v1
metadata:
  name: apache-service
  namespace: apachee
spec:
  selector:
      app: apache
  ports:
    - protocol: TCP
      port: 80 # exposed port in the cluster
      targetPort: 80 # container port
  type: ClusterIP