apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: backend
        image: venisasarah/fruits-backend:latest
        ports:
        - containerPort: 8000