apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: fastapi

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      name: frontend-pod
      namespace: fastapi
      labels:
        app: fastapi
    spec:
      containers:
      - name: frontend
        image: venisasarah/fruits-frontend:latest
        ports:
        - containerPort: 3000