kind: Deployment 
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: venisasarah/notes-app-k8s
        ports:
        - containerPort: 8000

#this is probes this will only check about the liveness, rediness and startup probes
        
        livenessProbe:
          httpGet:
            path: /
            port: 8000